### ISSUE TITLE
ZeroDivisionError

### ISSUE THREAD

**Issue by nickever** [thodnev/MonkeyTest#13]
```
Reading: 100.00 %Traceback (most recent call last):
  File "./monkeytest.py", line 193, in <module>
    main()
  File "./monkeytest.py", line 189, in main
    benchmark.print_result()
  File "./monkeytest.py", line 165, in print_result
    max=self.read_block_b / (1024 * 1024 * min(self.read_results)),
ZeroDivisionError: float division by zero
```

**Comment by peter-toft-greve** [comment]
I see the same - normal Ubuntu 22.04
